### ISSUE TITLE
Migration Swift 3 : Warning Delegate incompatibility

### ISSUE THREAD

**Issue by MathisDetourbet** [calimarkus/JDFlipNumberView#48]
Hi,

After the swift 3 migration, i got this following warning in the JDFlipImageView Class:
![capture d ecran 2016-09-27 a 12 38 26](https://cloud.githubusercontent.com/assets/5748462/18870056/512bc6a0-84af-11e6-8ae1-7045ebdeb57e.png)

How can I fix it?
Thanks for your help :)

**Comment by jaydee3** [comment]
We probably have to implement the CAAnimationDelegate explicitly. Happy to see a PR from you!
